dist: xenial
services:
  - postgresql
addons:
  postgresql: 9.6

node_js:
  - "13"

matrix:
    include:
        - name: "js lint"
          language: node_js
          node_js:
              - "node"
              - "13"
          script: "npm run lint:js"
        - name: "css lint"
          language: node_js
          node_js:
              - "node"
              - "13"
          script: "npm run lint:css"
        - name: "npm audit"
          language: node_js
          node_js:
              - "node"
              - "13"
          script: "npm run lint:audit"
        - name: "tests"
          language: node_js
          node_js:
              - "node"
              - "13"
          env:
              - NODE_ENV=tests
          install:
              - npm install
          before_script:
              - cp .env-dist .env
              - createdb test-blurts
              - npm install npm@latest -g

        - name: "l10n lint"
          language: python
          install:
              - sudo pip install compare-locales
          script:
              - moz-l10n-lint l10n.toml
              - compare-locales l10n.toml . `ls locales`

cache:
  npm: false
