dist: xenial
services:
  - postgresql
addons:
  postgresql: 9.6

matrix:
    include:
        - name: "lint"
          language: node_js
          node_js:
              - "node"
              - "lts/*"
          script: "npm-run-all lint:*"
        - name: "tests"
          language: node_js
          node_js:
              - "node"
              - "lts/*"
          env:
              - NODE_ENV=tests
          install:
              - npm install
          before_script:
              - cp .env-dist .env
              - createdb test-blurts
              - npm install npm@latest -g

        - name: "l10n lint"
          language: python
          install:
              - sudo pip install compare-locales
          script:
              - moz-l10n-lint l10n.toml
              - compare-locales l10n.toml . `ls locales`






